# Generated by Django 5.0.6 on 2024-05-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('oferta', models.BooleanField()),
                ('image', models.CharField(max_length=2555)),
            ],
        ),
    ]
