# Generated by Django 5.0.6 on 2024-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
