# Generated by Django 5.0.6 on 2024-05-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Lacteos',
        ),
    ]
