# Generated by Django 5.0.6 on 2024-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carniceria_cerveza_despensa_limpieza_mascotas_pan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carniceria',
        ),
        migrations.DeleteModel(
            name='Cerveza',
        ),
        migrations.DeleteModel(
            name='Despensa',
        ),
        migrations.DeleteModel(
            name='Limpieza',
        ),
        migrations.DeleteModel(
            name='Mascotas',
        ),
        migrations.DeleteModel(
            name='Pan',
        ),
        migrations.DeleteModel(
            name='Promos',
        ),
    ]
