# Generated by Django 5.0.6 on 2024-05-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_carniceria_delete_cerveza_delete_despensa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lacteos',
            new_name='Productos',
        ),
    ]
